sudo: required

language: c

compiler: gcc

#before_install:
#        - sudo apt-get -qq update

before_script:
        - cmake .

script:
        - make -j 4

after_script:
        - ./bin/wave time.wave
        - ls -al
        - file time.wav

notifications:
        email:
            - jwhu1024@gmail.com
                          
        on_success: change
        on_failure: always
